# This script is provided by github.com/bool64/dev.
name: breaking
on:
  pull_request:
env:
  GO111MODULE: "on"

jobs:
  broken-changes:
    concurrency:
      group: broken-changes-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install gorelease
        run: test -e ~/go/bin/gorelease || go install golang.org/x/exp/cmd/gorelease@latest
      - name: Check broken API changes
        run: gorelease -base=${{ env.GITHUB_BASE_REF }}
  examples:
    concurrency:
      group: examples-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build
        run: |
          cd examples
          go build ./...
