name: examples
on:
  push:
    branches:
      - master
      - release-*
  pull_request:
  workflow_dispatch:
jobs:
  examples:
    concurrency:
      group: examples-${{ github.ref }}-${{ matrix.go-version }}-${{ matrix.ydb-version }}-${{ matrix.driver }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go-version: [ 1.17.x, 1.18.x, 1.19.x, 1.20.x ]
        ydb-version: [ 22.5, 23.1 ]
        driver: [ native, database_sql, gorm ]
        exclude:
          - driver: database_sql
            go-version: 1.17.x
          - driver: gorm
            go-version: 1.17.x
    services:
      ydb:
        image: cr.yandex/yc/yandex-docker-local-ydb:${{ matrix.ydb-version }}-slim
        ports:
          - 2135:2135
          - 2136:2136
          - 8765:8765
        volumes:
          - /tmp/ydb_certs:/ydb_certs
        env:
          YDB_LOCAL_SURVIVE_RESTART: true
          YDB_USE_IN_MEMORY_PDISKS: true
        options: '-h localhost'
    env:
      OS: ubuntu-latest
      GO: ${{ matrix.go-version }}
      YDB_CONNECTION_STRING: grpc://localhost:2136/local
      YDB_ANONYMOUS_CREDENTIALS: 1
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true
      - name: Run examples for ${{ matrix.driver }}
        working-directory: ./examples/basic/${{ matrix.driver }}
        run: go run .
  examples-gorm-postgres:
    concurrency:
      group: examples-gorm-postgres-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: examples
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    env:
      OS: ubuntu-latest
      GO: 1.20.x
      POSTGRES_CONNECTION_STRING: postgres://postgres:postgres@localhost:5432/examples?sslmode=disable
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
          cache: true
      - name: Run examples for gorm with postgres
        working-directory: ./examples/basic/gorm
        run: go run .
  examples-gorm-sqlite:
    concurrency:
      group: examples-gorm-sqlite-${{ github.ref }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    env:
      OS: ubuntu-latest
      GO: 1.20.x
      SQLITE_CONNECTION_STRING: gorm.db
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.x
          cache: true
      - name: Run examples for gorm with sqlite
        working-directory: ./examples/basic/gorm
        run: go run .
