name: gtrace
on:
  push:
    tags:
      - v*
    branches:
      - master
      - '**'
  pull_request:
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        go: [1.14.x, 1.15.x, 1.16.x, 1.17.x]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go }}

    - name: Go Env
      run: |
        go env

    - name: Build
      run: |
        go install ./cmd/gtrace

    - name: Remove committed codegen file for recreate with gtrace on next step
      run: |
        rm ./cmd/gtrace/internal/test/*_gtrace.go

    - name: Generate
      run: |
        cd ./cmd/gtrace/internal/test/ && go generate

    - name: Test
      run: |
        go test -v ./cmd/gtrace/internal/test/
