name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  test:
    runs-on: [ ubuntu-latest, windows-latest ]
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '1.14'

    - name: Go Env
      run: |
        go env

    - name: Build
      run: |
        go install ./cmd/gtrace

    - name: Generate
      run: |
        gtrace -v -w ./test/test.go

    - name: Test
      run: |
        go test -v ./test
