on:
pull_request:
  branches: [main]

name: SLO

jobs:
  test-slo:
    if: github.event.pull_request.head.repo.full_name == 'ydb-platform/ydb-go-sdk'
    uses: ydb-platform/slo-tests/.github/workflows/slo.yml@main
    secrets: inherit
    with:
      language: go
      workload_path: tests/slo
