name: tests
on:
  push:
    tags:
      - v*
    branches:
      - master
      - '**'
  pull_request:
  workflow_dispatch:
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.14.x, 1.15.x, 1.16.x, 1.17.x]
        os: [ubuntu-latest]
    env:
      OS: ${{ matrix.os }}
      GO: ${{ matrix.go-version }}
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Test
        run: go test -race ./... -coverprofile=coverage.txt -covermode=atomic
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        if: matrix.os == 'ubuntu-latest' && matrix.go-version == '1.17.x' && github.ref == 'refs/heads/master'
        with:
          file: ./coverage.txt
          flags: unittests
          env_vars: OS,GO
          name: codecov
          fail_ci_if_error: true
          verbose: true